# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Verkcli < Formula
  desc "Inspect cameras, fetch thumbnails, and script Verkada APIs"
  homepage "https://github.com/ChrisVo/verkcli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ChrisVo/verkcli/releases/download/v0.1.0/verkcli_0.1.0_darwin_amd64.tar.gz"
      sha256 "2e241017ba704da5563fb52c41f92a1e80c347facadbc1cfa0e1be9351323805"

      def install
        bin.install "verkcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ChrisVo/verkcli/releases/download/v0.1.0/verkcli_0.1.0_darwin_arm64.tar.gz"
      sha256 "a2d672386e5d1e53f255c05c5f586c28532b727174030a696f309150367701d7"

      def install
        bin.install "verkcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisVo/verkcli/releases/download/v0.1.0/verkcli_0.1.0_linux_amd64.tar.gz"
      sha256 "626ea03950448379f4532a6fd6a2719f1e21d13f8277ab3e76dbcac491225923"
      def install
        bin.install "verkcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ChrisVo/verkcli/releases/download/v0.1.0/verkcli_0.1.0_linux_arm64.tar.gz"
      sha256 "db73678869aa8f46a1cbcadc5c1acd0594ef44bd342590dcc908ac0940691dc5"
      def install
        bin.install "verkcli"
      end
    end
  end

  test do
    system "#{bin}/verkcli", "version"
  end
end
